{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b102f11a-f68e-49f1-9e36-a4af3e4335ca",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "STEP 1 : GENERATE OUTLINE\n",
      "\n",
      "1. Introduction to Artificial Intelligence\n",
      "2. Applications of AI\n",
      "3. Advantages of AI\n",
      "4. Challenges in AI\n",
      "5. Future of AI\n",
      "\n",
      "STEP 2 : WRITE CONTENT\n",
      "\n",
      "\n",
      "Introduction to Artificial Intelligence\n",
      "Artificial Intelligence is a branch of computer science that enables machines to simulate human intelligence. It allows systems to perform tasks such as learning, reasoning, and decision-making.\n",
      "\n",
      "AI is widely used in industries like healthcare, education, finance, and transportation. It has become one of the most important technologies in the modern world.\n",
      "\n",
      "\n",
      "Applications of AI\n",
      "AI is used in virtual assistants, recommendation systems, and self-driving cars. These applications improve efficiency and user experience.\n",
      "\n",
      "In healthcare, AI helps doctors analyze medical data and detect diseases early. In business, it automates repetitive tasks and improves productivity.\n",
      "\n",
      "\n",
      "Advantages of AI\n",
      "AI can work continuously without fatigue, making processes faster and more accurate. It reduces human error in many tasks.\n",
      "\n",
      "Businesses use AI to save time and reduce operational costs. AI also helps in analyzing large amounts of data quickly.\n",
      "\n",
      "\n",
      "Challenges in AI\n",
      "One major challenge of AI is the risk of job displacement due to automation. Many repetitive jobs may be replaced by machines.\n",
      "\n",
      "Another challenge is data privacy and ethical concerns. AI systems require large amounts of data, which can raise security issues.\n",
      "\n",
      "\n",
      "Future of AI\n",
      "The future of AI is expected to bring more advanced automation and smarter technologies. AI may transform industries even further.\n",
      "\n",
      "Researchers are working to make AI systems more reliable, ethical, and transparent. AI will likely continue to influence daily life and business operations.\n",
      "\n",
      "STEP 3 : INTRODUCTION AND CONCLUSION\n",
      "\n",
      "Introduction:\n",
      "\n",
      "Artificial Intelligence is rapidly changing the world through smart technologies and automation. From healthcare to business, AI is improving efficiency and innovation. This blog explores the applications, benefits, challenges, and future of AI.\n",
      "\n",
      "Conclusion:\n",
      "\n",
      "Artificial Intelligence continues to shape the future of technology and society. While AI offers many advantages, it also presents important challenges that must be addressed. With responsible development, AI can create a smarter and more efficient world.\n",
      "\n",
      "ASSEMBLING FULL BLOG POST\n",
      "\n",
      "Blog post saved as blog_post.txt\n"
     ]
    }
   ],
   "source": [
    "topic = \"Artificial Intelligence\"\n",
    "\n",
    "print(\"STEP 1 : GENERATE OUTLINE\\n\")\n",
    "\n",
    "headings = [\n",
    "    \"Introduction to Artificial Intelligence\",\n",
    "    \"Applications of AI\",\n",
    "    \"Advantages of AI\",\n",
    "    \"Challenges in AI\",\n",
    "    \"Future of AI\"\n",
    "]\n",
    "\n",
    "for i, heading in enumerate(headings, start=1):\n",
    "    print(f\"{i}. {heading}\")\n",
    "\n",
    "print(\"\\nSTEP 2 : WRITE CONTENT\\n\")\n",
    "\n",
    "content = {\n",
    "    \"Introduction to Artificial Intelligence\":\n",
    "    [\n",
    "        \"Artificial Intelligence is a branch of computer science that enables machines to simulate human intelligence. It allows systems to perform tasks such as learning, reasoning, and decision-making.\",\n",
    "\n",
    "        \"AI is widely used in industries like healthcare, education, finance, and transportation. It has become one of the most important technologies in the modern world.\"\n",
    "    ],\n",
    "\n",
    "    \"Applications of AI\":\n",
    "    [\n",
    "        \"AI is used in virtual assistants, recommendation systems, and self-driving cars. These applications improve efficiency and user experience.\",\n",
    "\n",
    "        \"In healthcare, AI helps doctors analyze medical data and detect diseases early. In business, it automates repetitive tasks and improves productivity.\"\n",
    "    ],\n",
    "\n",
    "    \"Advantages of AI\":\n",
    "    [\n",
    "        \"AI can work continuously without fatigue, making processes faster and more accurate. It reduces human error in many tasks.\",\n",
    "\n",
    "        \"Businesses use AI to save time and reduce operational costs. AI also helps in analyzing large amounts of data quickly.\"\n",
    "    ],\n",
    "\n",
    "    \"Challenges in AI\":\n",
    "    [\n",
    "        \"One major challenge of AI is the risk of job displacement due to automation. Many repetitive jobs may be replaced by machines.\",\n",
    "\n",
    "        \"Another challenge is data privacy and ethical concerns. AI systems require large amounts of data, which can raise security issues.\"\n",
    "    ],\n",
    "\n",
    "    \"Future of AI\":\n",
    "    [\n",
    "        \"The future of AI is expected to bring more advanced automation and smarter technologies. AI may transform industries even further.\",\n",
    "\n",
    "        \"Researchers are working to make AI systems more reliable, ethical, and transparent. AI will likely continue to influence daily life and business operations.\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "for heading, paragraphs in content.items():\n",
    "    print(\"\\n\" + heading)\n",
    "    for para in paragraphs:\n",
    "        print(para)\n",
    "        print()\n",
    "\n",
    "print(\"STEP 3 : INTRODUCTION AND CONCLUSION\\n\")\n",
    "\n",
    "introduction = (\n",
    "    \"Artificial Intelligence is rapidly changing the world through smart technologies and automation. \"\n",
    "    \"From healthcare to business, AI is improving efficiency and innovation. \"\n",
    "    \"This blog explores the applications, benefits, challenges, and future of AI.\"\n",
    ")\n",
    "\n",
    "conclusion = (\n",
    "    \"Artificial Intelligence continues to shape the future of technology and society. \"\n",
    "    \"While AI offers many advantages, it also presents important challenges that must be addressed. \"\n",
    "    \"With responsible development, AI can create a smarter and more efficient world.\"\n",
    ")\n",
    "\n",
    "print(\"Introduction:\\n\")\n",
    "print(introduction)\n",
    "\n",
    "print(\"\\nConclusion:\\n\")\n",
    "print(conclusion)\n",
    "\n",
    "print(\"\\nASSEMBLING FULL BLOG POST\\n\")\n",
    "\n",
    "blog_post = f\"{topic}\\n\\n\"\n",
    "\n",
    "blog_post += \"INTRODUCTION\\n\"\n",
    "blog_post += introduction + \"\\n\\n\"\n",
    "\n",
    "for heading, paragraphs in content.items():\n",
    "    blog_post += heading + \"\\n\\n\"\n",
    "\n",
    "    for para in paragraphs:\n",
    "        blog_post += para + \"\\n\\n\"\n",
    "\n",
    "blog_post += \"CONCLUSION\\n\"\n",
    "blog_post += conclusion\n",
    "\n",
    "with open(\"blog_post.txt\", \"w\") as file:\n",
    "    file.write(blog_post)\n",
    "\n",
    "print(\"Blog post saved as blog_post.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e27bf09b-ac1f-4683-9e9d-917bec7386b8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
