{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a93642f6-cabc-45f8-b024-57a7228ebf34",
   "metadata": {},
   "outputs": [],
   "source": [
    "from groq import Groq\n",
    "\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a4ce9f8d-9004-484d-863c-b08b2a3e542a",
   "metadata": {},
   "outputs": [],
   "source": [
    "code_sample = \"\"\"\n",
    "def student_result(name, marks):\n",
    "\n",
    "    total = sum(marks)\n",
    "\n",
    "    average = total / len(marks)\n",
    "\n",
    "    if average >= 90:\n",
    "        grade = \"A\"\n",
    "\n",
    "    elif average >= 75:\n",
    "        grade = \"B\"\n",
    "\n",
    "    elif average >= 50:\n",
    "        grade = \"C\"\n",
    "\n",
    "    else:\n",
    "        grade = \"Fail\"\n",
    "\n",
    "    print(\"Student:\", name)\n",
    "    print(\"Total:\", total)\n",
    "    print(\"Average:\", average)\n",
    "    print(\"Grade:\", grade)\n",
    "\n",
    "student_result(\"Arya\", [95, 90, 98])\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a61dda9a-1471-496a-96ab-2de521a0025c",
   "metadata": {},
   "outputs": [],
   "source": [
    "zero_shot_prompt = f\"\"\"\n",
    "Review the following Python code and suggest improvements:\n",
    "\n",
    "{code_sample}\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f2cb2079-c4c7-4330-be8e-fae34c9973b1",
   "metadata": {},
   "outputs": [],
   "source": [
    "few_shot_prompt = f\"\"\"\n",
    "Example Review:\n",
    "\n",
    "Code:\n",
    "def add(a,b):\n",
    "    return a+b\n",
    "\n",
    "Review:\n",
    "- Add spaces after commas for readability.\n",
    "- Add a docstring explaining the function.\n",
    "- Handle invalid input types.\n",
    "\n",
    "Now review this code:\n",
    "\n",
    "{code_sample}\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "eaf43e7a-ff00-42a9-8fb2-6225952b6369",
   "metadata": {},
   "outputs": [],
   "source": [
    "chain_of_thought_prompt = f\"\"\"\n",
    "Review the following Python code step by step.\n",
    "\n",
    "Step 1: Check for bugs or logic errors.\n",
    "Step 2: Check coding style and readability.\n",
    "Step 3: Check security or input validation issues.\n",
    "Step 4: Suggest final improvements.\n",
    "\n",
    "Code:\n",
    "\n",
    "{code_sample}\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f949416e-f64e-4335-b595-d6eded273ecd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "Zero Shot\n",
      "======================================================================\n",
      "**Code Review and Improvements**\n",
      "\n",
      "The provided Python code calculates the average marks of a student and assigns a grade based on the average. Here are some suggestions to improve the code:\n",
      "\n",
      "### Separation of Concerns\n",
      "\n",
      "The function `student_result` is performing multiple tasks: calculating the average, determining the grade, and printing the result. It's better to separate these concerns into different functions for better maintainability and readability.\n",
      "\n",
      "### Input Validation\n",
      "\n",
      "The function does not validate the input. For example, it assumes that the `marks` list will always have at least one element. You should add checks to handle potential errors.\n",
      "\n",
      "### Magic Numbers\n",
      "\n",
      "The code uses magic numbers (e.g., 90, 75, 50) for determining the grade. These numbers could be replaced with named constants for better readability and maintainability.\n",
      "\n",
      "### Docstrings\n",
      "\n",
      "The function lacks docstrings, which provide a description of what the function does, what arguments it takes, and what it returns.\n",
      "\n",
      "### Code Organization\n",
      "\n",
      "The code is not organized in a clear and consistent manner. It's better to use blank lines to separate logical sections of the code and use consistent indentation.\n",
      "\n",
      "Here's the improved code:\n",
      "\n",
      "```python\n",
      "# Define a constant for the minimum marks required for each grade\n",
      "MIN_MARKS_FOR_A = 90\n",
      "MIN_MARKS_FOR_B = 75\n",
      "MIN_MARKS_FOR_C = 50\n",
      "\n",
      "def calculate_average(marks):\n",
      "    \"\"\"Calculate the average marks from a list of marks.\"\"\"\n",
      "    if not marks:\n",
      "        raise ValueError(\"Marks list cannot be empty\")\n",
      "    return sum(marks) / len(marks)\n",
      "\n",
      "def determine_grade(average):\n",
      "    \"\"\"Determine the grade based on the average marks.\"\"\"\n",
      "    if average >= MIN_MARKS_FOR_A:\n",
      "        return \"A\"\n",
      "    elif average >= MIN_MARKS_FOR_B:\n",
      "        return \"B\"\n",
      "    elif average >= MIN_MARKS_FOR_C:\n",
      "        return \"C\"\n",
      "    else:\n",
      "        return \"Fail\"\n",
      "\n",
      "def print_student_result(name, marks):\n",
      "    \"\"\"Print the student's result.\"\"\"\n",
      "    average = calculate_average(marks)\n",
      "    grade = determine_grade(average)\n",
      "    total = sum(marks)\n",
      "    print(\"Student:\", name)\n",
      "    print(\"Total:\", total)\n",
      "    print(\"Average:\", average)\n",
      "    print(\"Grade:\", grade)\n",
      "\n",
      "# Example usage:\n",
      "print_student_result(\"Arya\", [95, 90, 98])\n",
      "```\n",
      "\n",
      "This improved code is more readable, maintainable, and follows best practices for Python coding. The separate functions make it easier to modify or extend the code in the future.\n",
      "\n",
      "\n",
      "======================================================================\n",
      "Few Shot\n",
      "======================================================================\n",
      "Review:\n",
      "\n",
      "- **Code organization:** The code is performing multiple tasks: calculating the average, determining the grade, and printing the results. Consider breaking this down into separate functions for better modularity and reusability.\n",
      "\n",
      "- **Input validation:** The function does not handle invalid input types. For example, if the input for `name` is not a string or if the input for `marks` is not a list of numbers, the function may produce unexpected results or crash. Add checks to ensure the inputs are of the correct type.\n",
      "\n",
      "- **Docstrings:** The function lacks a docstring explaining its purpose, parameters, and return values.\n",
      "\n",
      "- **Readability:** The code uses a lot of nested if-else statements to determine the grade. Consider using a dictionary to map grade ranges to grades for better readability and maintainability.\n",
      "\n",
      "- **Error handling:** The function does not handle cases where the input list for `marks` is empty. Consider adding a check to handle this case.\n",
      "\n",
      "- **Redundant calculation:** The average is calculated twice: once as `total / len(marks)` and then again as `average`. Consider storing the result in a variable and reusing it.\n",
      "\n",
      "Here's an updated version of the code addressing these issues:\n",
      "\n",
      "```python\n",
      "def calculate_average(marks):\n",
      "    \"\"\"\n",
      "    Calculate the average of a list of numbers.\n",
      "\n",
      "    Args:\n",
      "        marks (list): A list of numbers.\n",
      "\n",
      "    Returns:\n",
      "        float: The average of the numbers.\n",
      "\n",
      "    Raises:\n",
      "        TypeError: If the input is not a list.\n",
      "        ValueError: If the input list is empty.\n",
      "    \"\"\"\n",
      "    if not isinstance(marks, list):\n",
      "        raise TypeError(\"Input must be a list\")\n",
      "    if len(marks) == 0:\n",
      "        raise ValueError(\"Input list cannot be empty\")\n",
      "    return sum(marks) / len(marks)\n",
      "\n",
      "\n",
      "def determine_grade(average):\n",
      "    \"\"\"\n",
      "    Determine the grade based on the average.\n",
      "\n",
      "    Args:\n",
      "        average (float): The average.\n",
      "\n",
      "    Returns:\n",
      "        str: The grade.\n",
      "    \"\"\"\n",
      "    grade_map = {\n",
      "        (90, float('inf')): \"A\",\n",
      "        (75, 90): \"B\",\n",
      "        (50, 75): \"C\",\n",
      "        (0, 50): \"Fail\"\n",
      "    }\n",
      "    for (lower, upper), grade in grade_map.items():\n",
      "        if lower <= average < upper:\n",
      "            return grade\n",
      "    return \"Unknown\"  # Should not reach here\n",
      "\n",
      "\n",
      "def print_student_result(name, marks):\n",
      "    \"\"\"\n",
      "    Print the student result.\n",
      "\n",
      "    Args:\n",
      "        name (str): The student's name.\n",
      "        marks (list): A list of numbers representing the student's marks.\n",
      "    \"\"\"\n",
      "    try:\n",
      "        average = calculate_average(marks)\n",
      "        grade = determine_grade(average)\n",
      "        print(\"Student:\", name)\n",
      "        print(\"Total:\", sum(marks))\n",
      "        print(\"Average:\", average)\n",
      "        print(\"Grade:\", grade)\n",
      "    except (TypeError, ValueError) as e:\n",
      "        print(\"Error:\", e)\n",
      "\n",
      "\n",
      "print_student_result(\"Arya\", [95, 90, 98])\n",
      "```\n",
      "\n",
      "This updated code is more modular, readable, and maintainable. It also includes input validation and error handling.\n",
      "\n",
      "\n",
      "======================================================================\n",
      "Chain of Thought\n",
      "======================================================================\n",
      "**Step 1: Check for bugs or logic errors**\n",
      "\n",
      "The code provided seems to be logically correct and does not contain any syntax errors. However, there are a few potential issues:\n",
      "\n",
      "*   The code does not handle the case where the input `marks` is empty. This will result in a `ZeroDivisionError` when trying to calculate the average.\n",
      "*   The code does not handle the case where the input `marks` is not a list or tuple. This will result in a `TypeError` when trying to calculate the average.\n",
      "*   The code does not handle the case where the input `marks` contains non-numeric values. This will result in a `TypeError` when trying to calculate the average.\n",
      "\n",
      "**Step 2: Check coding style and readability**\n",
      "\n",
      "The code is generally well-structured, but there are a few areas for improvement:\n",
      "\n",
      "*   The function name `student_result` is not very descriptive. A more descriptive name like `calculate_student_grades` would be better.\n",
      "*   The variable names `total` and `average` are not very descriptive. More descriptive names like `total_marks` and `average_marks` would be better.\n",
      "*   The function does not return the calculated grades. Instead, it prints them directly. Consider returning the grades as a dictionary or a named tuple.\n",
      "*   There are multiple print statements in the function. Consider using a logging framework or a more flexible logging system.\n",
      "\n",
      "**Step 3: Check security or input validation issues**\n",
      "\n",
      "The code does not perform any input validation, which makes it vulnerable to security issues:\n",
      "\n",
      "*   The function does not check if the input `name` is a string. This could result in a `TypeError` if the input is not a string.\n",
      "*   The function does not check if the input `marks` is a list or tuple. This could result in a `TypeError` if the input is not a list or tuple.\n",
      "*   The function does not check if the input `marks` contains non-numeric values. This could result in a `TypeError` when trying to calculate the average.\n",
      "\n",
      "**Step 4: Suggest final improvements**\n",
      "\n",
      "Here's an improved version of the code:\n",
      "\n",
      "```python\n",
      "def calculate_student_grades(name: str, marks: list[float]) -> dict[str, float]:\n",
      "    \"\"\"\n",
      "    Calculate the total marks, average marks, and grade for a student.\n",
      "\n",
      "    Args:\n",
      "        name (str): The name of the student.\n",
      "        marks (list[float]): A list of marks obtained by the student.\n",
      "\n",
      "    Returns:\n",
      "        dict[str, float]: A dictionary containing the total marks, average marks, and grade.\n",
      "    \"\"\"\n",
      "\n",
      "    # Check if the input marks is a list\n",
      "    if not isinstance(marks, list):\n",
      "        raise ValueError(\"Marks must be a list\")\n",
      "\n",
      "    # Check if the input marks is not empty\n",
      "    if len(marks) == 0:\n",
      "        raise ValueError(\"Marks cannot be empty\")\n",
      "\n",
      "    # Check if all elements in the input marks are numeric\n",
      "    if not all(isinstance(mark, (int, float)) for mark in marks):\n",
      "        raise ValueError(\"All marks must be numeric\")\n",
      "\n",
      "    # Calculate the total marks\n",
      "    total_marks = sum(marks)\n",
      "\n",
      "    # Calculate the average marks\n",
      "    average_marks = total_marks / len(marks)\n",
      "\n",
      "    # Determine the grade based on the average marks\n",
      "    if average_marks >= 90:\n",
      "        grade = \"A\"\n",
      "    elif average_marks >= 75:\n",
      "        grade = \"B\"\n",
      "    elif average_marks >= 50:\n",
      "        grade = \"C\"\n",
      "    else:\n",
      "        grade = \"Fail\"\n",
      "\n",
      "    # Return the calculated grades\n",
      "    return {\n",
      "        \"name\": name,\n",
      "        \"total_marks\": total_marks,\n",
      "        \"average_marks\": average_marks,\n",
      "        \"grade\": grade,\n",
      "    }\n",
      "\n",
      "# Example usage:\n",
      "student_grades = calculate_student_grades(\"Arya\", [95, 90, 98])\n",
      "print(student_grades)\n",
      "```\n",
      "\n",
      "This improved version includes:\n",
      "\n",
      "*   Input validation to ensure that the input `marks` is a list and contains only numeric values.\n",
      "*   A more descriptive function name and variable names.\n",
      "*   A return statement to return the calculated grades as a dictionary.\n",
      "*   A docstring to document the function's behavior and parameters.\n",
      "*   Example usage to demonstrate how to use the function.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "prompts = {\n",
    "    \"Zero Shot\": zero_shot_prompt,\n",
    "    \"Few Shot\": few_shot_prompt,\n",
    "    \"Chain of Thought\": chain_of_thought_prompt\n",
    "}\n",
    "\n",
    "for name, prompt in prompts.items():\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=[\n",
    "            {\n",
    "                \"role\": \"user\",\n",
    "                \"content\": prompt\n",
    "            }\n",
    "        ],\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    print(\"=\" * 70)\n",
    "    print(name)\n",
    "    print(\"=\" * 70)\n",
    "\n",
    "    print(response.choices[0].message.content)\n",
    "    print(\"\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2617ad12-c10f-4ef6-aaa8-1e53d0d958bb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
