{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9930c7f2-ddee-485a-a797-1c837d775e36",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: groq in /opt/anaconda3/lib/python3.12/site-packages (1.2.0)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (4.2.0)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (1.9.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (0.27.0)\n",
      "Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (2.8.2)\n",
      "Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.12/site-packages (from groq) (1.3.0)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.14 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (4.14.0)\n",
      "Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.12/site-packages (from anyio<5,>=3.5.0->groq) (3.7)\n",
      "Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (1.0.2)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /opt/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.14.0)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (2.20.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade groq"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "7fd96845-6336-4ef5-bea0-48cb8c810d2d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "Temperature: 0.1\n",
      "============================================================\n",
      "**Recursion: A Real-World Example**\n",
      "\n",
      "Recursion is a programming technique where a function calls itself repeatedly until it reaches a base case that stops the recursion. This technique is useful for solving problems that have a recursive structure, such as tree traversals, factorial calculations, and more.\n",
      "\n",
      "**Example: Calculating the Total Number of Folders in a File System**\n",
      "\n",
      "Imagine you have a file system with folders and subfolders. You want to write a function that calculates the total number of folders in the file system.\n",
      "\n",
      "**Recursive Solution**\n",
      "\n",
      "Here's a recursive solution in Python:\n",
      "```python\n",
      "def count_folders(folder):\n",
      "    # Base case: if the folder is empty, return 0\n",
      "    if not folder:\n",
      "        return 0\n",
      "    \n",
      "    # Count the current folder\n",
      "    count = 1\n",
      "    \n",
      "    # Recursively count the subfolders\n",
      "    for subfolder in folder:\n",
      "        count += count_folders(subfolder)\n",
      "    \n",
      "    return count\n",
      "```\n",
      "**How it Works**\n",
      "\n",
      "1. The function `count_folders` takes a folder as input.\n",
      "2. If the folder is empty (i.e., `not folder` is `True`), the function returns 0, which is the base case.\n",
      "3. Otherwise, the function counts the current folder by incrementing the `count` variable by 1.\n",
      "4. The function then recursively calls itself for each subfolder in the current folder.\n",
      "5. The recursive calls return the total number of folders in each subfolder.\n",
      "6. The function adds up the counts from the recursive calls and returns the total number of folders.\n",
      "\n",
      "**Example Use Case**\n",
      "\n",
      "Suppose we have the following file system:\n",
      "```python\n",
      "folder = [\n",
      "    {'name': 'Folder 1', 'subfolders': [\n",
      "        {'name': 'Subfolder 1', 'subfolders': []},\n",
      "        {'name': 'Subfolder 2', 'subfolders': []}\n",
      "    ]},\n",
      "    {'name': 'Folder 2', 'subfolders': [\n",
      "        {'name': 'Subfolder 3', 'subfolders': [\n",
      "            {'name': 'Subfolder 4', 'subfolders': []}\n",
      "        ]}\n",
      "    ]}\n",
      "]\n",
      "```\n",
      "We can call the `count_folders` function like this:\n",
      "```python\n",
      "total_folders = count_folders(folder)\n",
      "print(total_folders)  # Output: 6\n",
      "```\n",
      "The function will recursively traverse the file system and return the total number of folders, which is 6.\n",
      "\n",
      "**Benefits of Recursion**\n",
      "\n",
      "Recursion can be a powerful technique for solving problems with a recursive structure. Some benefits of recursion include:\n",
      "\n",
      "* **Elegant code**: Recursive solutions can be more concise and elegant than iterative solutions.\n",
      "* **Easy to understand**: Recursive solutions can be easier to understand, especially for problems with a recursive structure.\n",
      "* **Efficient**: Recursive solutions can be more efficient than iterative solutions for large inputs.\n",
      "\n",
      "However, recursion can also have some drawbacks, such as:\n",
      "\n",
      "* **Stack overflow**: Recursive solutions can cause a stack overflow if the recursion is too deep.\n",
      "* **Difficulty in debugging**: Recursive solutions can be more difficult to debug than iterative solutions.\n",
      "\n",
      "In summary, recursion is a powerful technique for solving problems with a recursive structure. While it can be elegant and efficient, it requires careful consideration of the base case and the recursive calls to avoid stack overflows and other issues.\n",
      "\n",
      "============================================================\n",
      "Temperature: 0.7\n",
      "============================================================\n",
      "**Recursion Explained with a Real-World Example**\n",
      "\n",
      "Recursion is a programming technique where a function calls itself repeatedly until it reaches a base case that stops the recursion. It's a powerful tool for solving problems that have a recursive structure, where a problem can be broken down into smaller sub-problems of the same type.\n",
      "\n",
      "**Real-World Example: Calculating the Total Number of Enrolled Students in a School**\n",
      "\n",
      "Imagine you're the principal of a school, and you want to calculate the total number of students enrolled in the school. The school has multiple departments, each of which has multiple classes, and each class has multiple students. You can use recursion to calculate the total number of students enrolled in the school.\n",
      "\n",
      "**Recursive Function**\n",
      "\n",
      "Here's a recursive function in Python that calculates the total number of students enrolled in the school:\n",
      "```python\n",
      "class Department:\n",
      "    def __init__(self, name, classes=None):\n",
      "        self.name = name\n",
      "        self.classes = classes if classes else []\n",
      "\n",
      "    def get_total_students(self):\n",
      "        total_students = 0\n",
      "        for class_ in self.classes:\n",
      "            total_students += class_.get_total_students()\n",
      "        return total_students\n",
      "\n",
      "class Class:\n",
      "    def __init__(self, name, students=None):\n",
      "        self.name = name\n",
      "        self.students = students if students else []\n",
      "\n",
      "    def get_total_students(self):\n",
      "        return len(self.students)\n",
      "\n",
      "# Create a school with departments and classes\n",
      "school = Department(\"School\")\n",
      "department1 = Department(\"Department 1\")\n",
      "department2 = Department(\"Department 2\")\n",
      "school.classes = [department1, department2]\n",
      "\n",
      "department1.classes = [\n",
      "    Class(\"Class 1\", [Student(\"Alice\"), Student(\"Bob\")]),\n",
      "    Class(\"Class 2\", [Student(\"Charlie\"), Student(\"David\")])\n",
      "]\n",
      "\n",
      "department2.classes = [\n",
      "    Class(\"Class 3\", [Student(\"Eve\"), Student(\"Frank\")]),\n",
      "    Class(\"Class 4\", [Student(\"George\"), Student(\"Hannah\")])\n",
      "]\n",
      "\n",
      "# Calculate the total number of students enrolled in the school\n",
      "total_students = school.get_total_students()\n",
      "print(total_students)\n",
      "```\n",
      "**How Recursion Works**\n",
      "\n",
      "In this example, the `get_total_students` method in the `Department` class is recursive. It iterates over each class in the department and calls the `get_total_students` method on each class. This process repeats until it reaches a `Class` object, which simply returns the number of students in that class.\n",
      "\n",
      "The recursion unwinds when the `get_total_students` method is called on a `Class` object, at which point it returns the number of students in that class.\n",
      "\n",
      "**Base Case**\n",
      "\n",
      "The base case in this example is when the `get_total_students` method is called on a `Class` object, at which point it returns the number of students in that class. This is the point at which the recursion stops and the method returns a value.\n",
      "\n",
      "**Advantages of Recursion**\n",
      "\n",
      "Recursion has several advantages, including:\n",
      "\n",
      "*   **Elegant solution**: Recursion can lead to elegant and concise solutions to complex problems.\n",
      "*   **Easy to understand**: Recursive functions can be easier to understand than iterative solutions, especially for problems with a recursive structure.\n",
      "*   **Flexible**: Recursion can be used to solve a wide range of problems, from simple arithmetic calculations to complex algorithmic problems.\n",
      "\n",
      "**Disadvantages of Recursion**\n",
      "\n",
      "However, recursion also has some disadvantages, including:\n",
      "\n",
      "*   **Stack overflow**: Deep recursion can lead to a stack overflow error, which can cause the program to crash.\n",
      "*   **Performance**: Recursion can be slower than iteration, especially for large inputs.\n",
      "*   **Complexity**: Recursive functions can be more difficult to debug and optimize than iterative solutions.\n",
      "\n",
      "============================================================\n",
      "Temperature: 1.0\n",
      "============================================================\n",
      "Recursion is a fundamental concept in programming where a function calls itself repeatedly until it reaches a base case that stops the recursion. This concept mirrors real-life problems where a task is broken down into smaller sub-tasks until we reach a point where no further breakdown is needed.\n",
      "\n",
      "**Example: Calculating the Total Value of a Recursive Nesting Box**\n",
      "\n",
      "Let's say you have a nesting box with a series of boxes inside each other. Each box has a different size, and you want to calculate the total value of all the boxes in the nesting system. One way to approach this problem is to use recursion.\n",
      "\n",
      "Here's an example implementation in Python:\n",
      "\n",
      "```python\n",
      "class Box:\n",
      "    def __init__(self, name, value, sub_boxes=None):\n",
      "        self.name = name\n",
      "        self.value = value\n",
      "        self.sub_boxes = sub_boxes if sub_boxes else []\n",
      "\n",
      "    def calculate_value(self):\n",
      "        total_value = self.value\n",
      "        if self.sub_boxes:\n",
      "            for sub_box in self.sub_boxes:\n",
      "                total_value += sub_box.calculate_value()\n",
      "        return total_value\n",
      "\n",
      "# Example usage:\n",
      "root_box = Box(\"Root\", 1000)\n",
      "box_1 = Box(\"Box 1\", 300, [Box(\"Box 11\", 50), Box(\"Box 12\", 150)])\n",
      "box_2 = Box(\"Box 2\", 200, [Box(\"Box 21\", 75), Box(\"Box 22\", 125)])\n",
      "\n",
      "root_box.sub_boxes = [box_1, box_2]\n",
      "\n",
      "print(root_box.calculate_value())  # Output: 1963\n",
      "```\n",
      "\n",
      "In this example:\n",
      "\n",
      "1. We define a `Box` class with properties like `name`, `value`, and a list of `sub_boxes`.\n",
      "2. The `calculate_value` method recursively adds up the value of all the boxes in the nesting system.\n",
      "3. We create a root box with two sub-boxes, each with their own sub-boxes.\n",
      "4. We call `calculate_value` on the root box to get the total value of all boxes.\n",
      "\n",
      "**Recursive Breakdown**\n",
      "\n",
      "Here's how the recursion unfolds:\n",
      "\n",
      "1. `calculate_value` is called on the root box.\n",
      "2. The root box has two sub-boxes (box_1 and box_2), so we call `calculate_value` on each of them.\n",
      "3. box_1 has two sub-boxes (box_11 and box_12), so we call `calculate_value` on each of them recursively.\n",
      "4. box_11 doesn't have any sub-boxes, so it returns its value directly.\n",
      "5. box_12 doesn't have any sub-boxes, so it returns its value directly.\n",
      "6. box_1 aggregates the values of box_11 and box_12 and returns the total value.\n",
      "7. box_2 has two sub-boxes (box_21 and box_22), so we call `calculate_value` on each of them recursively.\n",
      "8. box_21 doesn't have any sub-boxes, so it returns its value directly.\n",
      "9. box_22 doesn't have any sub-boxes, so it returns its value directly.\n",
      "10. box_2 aggregates the values of box_21 and box_22 and returns the total value.\n",
      "11. The root box aggregates the values of box_1 and box_2 and returns the total value of all boxes.\n",
      "\n",
      "By using recursion, we can break down the problem of calculating the total value of a recursive nesting box into smaller, more manageable sub-problems.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")\n",
    "\n",
    "question = \"Explain recursion with a real-world example\"\n",
    "\n",
    "temperatures = [0.1, 0.7, 1.0]\n",
    "\n",
    "for temp in temperatures:\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=[\n",
    "            {\n",
    "                \"role\": \"user\",\n",
    "                \"content\": question\n",
    "            }\n",
    "        ],\n",
    "        temperature=temp\n",
    "    )\n",
    "\n",
    "    print(\"=\" * 60)\n",
    "    print(\"Temperature:\", temp)\n",
    "    print(\"=\" * 60)\n",
    "\n",
    "    print(response.choices[0].message.content)\n",
    "    print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "67827193-e2e9-4dd4-8af1-9684e941fd4d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Observation:\n",
      "\n",
      "At temperature 0.1, the response is usually more focused, predictable,\n",
      "and consistent.\n",
      "\n",
      "At temperature 0.7, the explanation becomes more natural and slightly\n",
      "creative while still staying accurate.\n",
      "\n",
      "At temperature 1.0, the response becomes highly creative and varied,\n",
      "but it may also become less consistent or include unusual examples.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(\"\"\"\n",
    "Observation:\n",
    "\n",
    "At temperature 0.1, the response is usually more focused, predictable,\n",
    "and consistent.\n",
    "\n",
    "At temperature 0.7, the explanation becomes more natural and slightly\n",
    "creative while still staying accurate.\n",
    "\n",
    "At temperature 1.0, the response becomes highly creative and varied,\n",
    "but it may also become less consistent or include unusual examples.\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88ec9eb8-7555-42cb-a089-aa900ad2bdb9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
