{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "1e83cad4-d451-4452-a308-980bf76cb676",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "TEST 1 : COMPLEX REASONING QUESTION\n",
      "\n",
      "================================================================================\n",
      "PROMPT\n",
      "================================================================================\n",
      "\n",
      "A farmer has 17 sheep. All but 9 die.\n",
      "How many sheep are left and explain the reasoning step by step.\n",
      "\n",
      "\n",
      "================================================================================\n",
      "MODEL COMPARISON\n",
      "================================================================================\n",
      "\n",
      "Model: llama-3.1-8b-instant\n",
      "Response Time: 0.92 seconds\n",
      "Output Length: 1059 characters\n",
      "\n",
      "Response:\n",
      "To find out how many sheep are left, we need to perform a simple subtraction.\n",
      "\n",
      "Step 1: The farmer initially has 17 sheep.\n",
      "Step 2: All but 9 die, which means 9 sheep remain.\n",
      "Step 3: Therefore, to find the number of sheep left, we subtract the number of sheep that died from the initial number of sheep.\n",
      "\n",
      "However, we can also interpret this as the farmer losing most of the sheep but 9 remaining so we do the following:\n",
      "\n",
      "17 (initial number of sheep) - (number of sheep that were lost) = number of sheep remaining.\n",
      " \n",
      "To find the number of sheep that were lost, we subtract the number of sheep that remained from the initial number of sheep. However, we are not directly given that number but we are told that \"All but 9 die.\" So we are looking for the value of \"x\" in this equation:\n",
      "9 + x = 17\n",
      "\n",
      "To find \"x\":\n",
      "- x = 17 - 9\n",
      "- x = 8\n",
      "\n",
      "This means 8 sheep died. So we subtract the number of sheep that died from the initial number of sheep to find the number of sheep left.\n",
      "\n",
      "17 (initial number of sheep) - 8 (number of sheep that died) = 9\n",
      "\n",
      "Therefore, 9 sheep are left.\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "Model: llama-3.3-70b-versatile\n",
      "Response Time: 0.59 seconds\n",
      "Output Length: 617 characters\n",
      "\n",
      "Response:\n",
      "To find out how many sheep are left, we need to understand the statement \"All but 9 die.\" This means that 9 sheep will survive, and all the rest will die. \n",
      "\n",
      "Here's the step-by-step reasoning:\n",
      "\n",
      "1. The farmer starts with 17 sheep.\n",
      "2. The statement \"All but 9 die\" implies that 9 sheep are exempt from dying.\n",
      "3. To find out how many sheep die, we subtract the number of sheep that survive (9) from the total number of sheep (17). \n",
      "   17 (total sheep) - 9 (sheep that survive) = 8\n",
      "   This means 8 sheep die.\n",
      "4. Since 9 sheep are left alive, the number of sheep that are left is 9.\n",
      "\n",
      "Therefore, the farmer has 9 sheep left.\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "TEST 2 : SIMPLE FACTUAL QUESTION\n",
      "\n",
      "================================================================================\n",
      "PROMPT\n",
      "================================================================================\n",
      "\n",
      "What is the capital of Japan?\n",
      "\n",
      "\n",
      "================================================================================\n",
      "MODEL COMPARISON\n",
      "================================================================================\n",
      "\n",
      "Model: llama-3.1-8b-instant\n",
      "Response Time: 0.22 seconds\n",
      "Output Length: 30 characters\n",
      "\n",
      "Response:\n",
      "The capital of Japan is Tokyo.\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "Model: llama-3.3-70b-versatile\n",
      "Response Time: 0.21 seconds\n",
      "Output Length: 30 characters\n",
      "\n",
      "Response:\n",
      "The capital of Japan is Tokyo.\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "OBSERVATIONS\n",
      "\n",
      "1. llama3-8b-8192 is usually faster and gives shorter responses.\n",
      "2. llama3-70b-8192 is slower but often provides more detailed reasoning.\n",
      "3. For simple factual questions, the smaller model is usually enough.\n",
      "4. For complex reasoning, coding help, or detailed explanations, the 70B model is often worth the extra response time.\n",
      "5. The larger model generally produces clearer and more accurate multi-step reasoning.\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "from groq import Groq\n",
    "\n",
    "client = Groq(api_key=\"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\")\n",
    "\n",
    "def compare_models(prompt, models):\n",
    "    results = []\n",
    "\n",
    "    for model in models:\n",
    "        start_time = time.time()\n",
    "\n",
    "        response = client.chat.completions.create(\n",
    "            model=model,\n",
    "            messages=[\n",
    "                {\"role\": \"user\", \"content\": prompt}\n",
    "            ]\n",
    "        )\n",
    "\n",
    "        end_time = time.time()\n",
    "\n",
    "        output = response.choices[0].message.content\n",
    "        response_time = end_time - start_time\n",
    "        output_length = len(output)\n",
    "\n",
    "        results.append({\n",
    "            \"model\": model,\n",
    "            \"time\": response_time,\n",
    "            \"length\": output_length,\n",
    "            \"output\": output\n",
    "        })\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 80)\n",
    "    print(\"PROMPT\")\n",
    "    print(\"=\" * 80)\n",
    "    print(prompt)\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 80)\n",
    "    print(\"MODEL COMPARISON\")\n",
    "    print(\"=\" * 80)\n",
    "\n",
    "    for result in results:\n",
    "        print(f\"\\nModel: {result['model']}\")\n",
    "        print(f\"Response Time: {result['time']:.2f} seconds\")\n",
    "        print(f\"Output Length: {result['length']} characters\")\n",
    "\n",
    "        print(\"\\nResponse:\")\n",
    "        print(result[\"output\"])\n",
    "        print(\"-\" * 80)\n",
    "\n",
    "models = [\n",
    "    \"llama-3.1-8b-instant\",\n",
    "    \"llama-3.3-70b-versatile\"\n",
    "]\n",
    "\n",
    "complex_prompt = \"\"\"\n",
    "A farmer has 17 sheep. All but 9 die.\n",
    "How many sheep are left and explain the reasoning step by step.\n",
    "\"\"\"\n",
    "\n",
    "simple_prompt = \"\"\"\n",
    "What is the capital of Japan?\n",
    "\"\"\"\n",
    "\n",
    "print(\"\\nTEST 1 : COMPLEX REASONING QUESTION\")\n",
    "compare_models(complex_prompt, models)\n",
    "\n",
    "print(\"\\nTEST 2 : SIMPLE FACTUAL QUESTION\")\n",
    "compare_models(simple_prompt, models)\n",
    "print(\"\\nOBSERVATIONS\\n\")\n",
    "\n",
    "print(\"1. llama3-8b-8192 is usually faster and gives shorter responses.\")\n",
    "print(\"2. llama3-70b-8192 is slower but often provides more detailed reasoning.\")\n",
    "print(\"3. For simple factual questions, the smaller model is usually enough.\")\n",
    "print(\"4. For complex reasoning, coding help, or detailed explanations, the 70B model is often worth the extra response time.\")\n",
    "print(\"5. The larger model generally produces clearer and more accurate multi-step reasoning.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e7ffd623-8c42-4d9b-b99a-42941e810601",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
