{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c0f9c984-148f-4797-90bd-eea30e3a382b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "STEP 1 : GENERATE QUIZ QUESTIONS\n",
      "\n",
      "1. What is a Python list?\n",
      "2. How do you add an element to a list?\n",
      "3. How do you access the first element in a list?\n",
      "4. What is the difference between append() and extend()?\n",
      "\n",
      "STEP 2 : GENERATE MODEL ANSWERS\n",
      "\n",
      "1. What is a Python list?\n",
      "Model Answer: A Python list is an ordered, mutable collection used to store multiple items.\n",
      "\n",
      "2. How do you add an element to a list?\n",
      "Model Answer: You can add an element using append(). Example: my_list.append(10)\n",
      "\n",
      "3. How do you access the first element in a list?\n",
      "Model Answer: Use index 0 to access the first element. Example: my_list[0]\n",
      "\n",
      "4. What is the difference between append() and extend()?\n",
      "Model Answer: append() adds a single element, while extend() adds multiple elements from another iterable.\n",
      "\n",
      "STEP 3 : EVALUATE STUDENT ANSWERS\n",
      "\n",
      "1. What is a Python list?\n",
      "Student Answer:\n",
      "A list is used only for numbers.\n",
      "Correct Answer:\n",
      "A Python list is an ordered, mutable collection used to store multiple items.\n",
      "Score: 4 /10\n",
      "Feedback: List can store different data types, not only numbers.\n",
      "\n",
      "2. How do you add an element to a list?\n",
      "Student Answer:\n",
      "We use additem() function.\n",
      "Correct Answer:\n",
      "You can add an element using append(). Example: my_list.append(10)\n",
      "Score: 2 /10\n",
      "Feedback: Python lists use append(), not additem().\n",
      "\n",
      "3. How do you access the first element in a list?\n",
      "Student Answer:\n",
      "First element is accessed using index 1.\n",
      "Correct Answer:\n",
      "Use index 0 to access the first element. Example: my_list[0]\n",
      "Score: 3 /10\n",
      "Feedback: Python indexing starts from 0, not 1.\n",
      "\n",
      "4. What is the difference between append() and extend()?\n",
      "Student Answer:\n",
      "append() and extend() are exactly the same.\n",
      "Correct Answer:\n",
      "append() adds a single element, while extend() adds multiple elements from another iterable.\n",
      "Score: 2 /10\n",
      "Feedback: append() adds one item, extend() adds multiple items.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "topic = \"Python lists\"\n",
    "\n",
    "print(\"STEP 1 : GENERATE QUIZ QUESTIONS\\n\")\n",
    "\n",
    "questions = [\n",
    "    \"1. What is a Python list?\",\n",
    "    \"2. How do you add an element to a list?\",\n",
    "    \"3. How do you access the first element in a list?\",\n",
    "    \"4. What is the difference between append() and extend()?\"\n",
    "]\n",
    "\n",
    "for q in questions:\n",
    "    print(q)\n",
    "\n",
    "print(\"\\nSTEP 2 : GENERATE MODEL ANSWERS\\n\")\n",
    "\n",
    "model_answers = {\n",
    "    questions[0]:\n",
    "    \"A Python list is an ordered, mutable collection used to store multiple items.\",\n",
    "\n",
    "    questions[1]:\n",
    "    \"You can add an element using append(). Example: my_list.append(10)\",\n",
    "\n",
    "    questions[2]:\n",
    "    \"Use index 0 to access the first element. Example: my_list[0]\",\n",
    "\n",
    "    questions[3]:\n",
    "    \"append() adds a single element, while extend() adds multiple elements from another iterable.\"\n",
    "}\n",
    "\n",
    "for question, answer in model_answers.items():\n",
    "    print(question)\n",
    "    print(\"Model Answer:\", answer)\n",
    "    print()\n",
    "\n",
    "print(\"STEP 3 : EVALUATE STUDENT ANSWERS\\n\")\n",
    "\n",
    "student_answers = {\n",
    "    questions[0]:\n",
    "    \"A list is used only for numbers.\",\n",
    "\n",
    "    questions[1]:\n",
    "    \"We use additem() function.\",\n",
    "\n",
    "    questions[2]:\n",
    "    \"First element is accessed using index 1.\",\n",
    "\n",
    "    questions[3]:\n",
    "    \"append() and extend() are exactly the same.\"\n",
    "}\n",
    "\n",
    "for question in questions:\n",
    "    print(question)\n",
    "\n",
    "    print(\"Student Answer:\")\n",
    "    print(student_answers[question])\n",
    "\n",
    "    print(\"Correct Answer:\")\n",
    "    print(model_answers[question])\n",
    "\n",
    "    if question == questions[0]:\n",
    "        score = 4\n",
    "        feedback = \"List can store different data types, not only numbers.\"\n",
    "\n",
    "    elif question == questions[1]:\n",
    "        score = 2\n",
    "        feedback = \"Python lists use append(), not additem().\"\n",
    "\n",
    "    elif question == questions[2]:\n",
    "        score = 3\n",
    "        feedback = \"Python indexing starts from 0, not 1.\"\n",
    "\n",
    "    else:\n",
    "        score = 2\n",
    "        feedback = \"append() adds one item, extend() adds multiple items.\"\n",
    "\n",
    "    print(\"Score:\", score, \"/10\")\n",
    "    print(\"Feedback:\", feedback)\n",
    "    print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7296218a-d284-4691-aa9c-8f05f3199b45",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
