{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0ad4a547-5c10-438f-84b0-d6a6640f6cd1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: groq in /opt/anaconda3/lib/python3.12/site-packages (1.2.0)\n",
      "Requirement already satisfied: tiktoken in /opt/anaconda3/lib/python3.12/site-packages (0.13.0)\n",
      "Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.2)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (4.2.0)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (1.9.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (0.27.0)\n",
      "Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (2.8.2)\n",
      "Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.12/site-packages (from groq) (1.3.0)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.14 in /opt/anaconda3/lib/python3.12/site-packages (from groq) (4.14.0)\n",
      "Requirement already satisfied: regex in /opt/anaconda3/lib/python3.12/site-packages (from tiktoken) (2024.9.11)\n",
      "Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from tiktoken) (2.32.3)\n",
      "Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)\n",
      "Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.12/site-packages (from anyio<5,>=3.5.0->groq) (3.7)\n",
      "Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->groq) (1.0.2)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /opt/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.14.0)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->groq) (2.20.1)\n",
      "Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->tiktoken) (3.3.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->tiktoken) (2.2.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install groq tiktoken pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1aac5dfc-ca15-4718-ada3-47a90c23988d",
   "metadata": {},
   "outputs": [],
   "source": [
    "from groq import Groq\n",
    "import tiktoken\n",
    "import pandas as pd\n",
    "import time\n",
    "\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")\n",
    "\n",
    "encoding = tiktoken.get_encoding(\"cl100k_base\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9df35d7a-322b-4993-a6e8-5587bbd6e546",
   "metadata": {},
   "outputs": [],
   "source": [
    "code_sample = \"\"\"\n",
    "def student_result(name, marks):\n",
    "\n",
    "    total = sum(marks)\n",
    "\n",
    "    average = total / len(marks)\n",
    "\n",
    "    if average >= 90:\n",
    "        grade = \"A\"\n",
    "\n",
    "    elif average >= 75:\n",
    "        grade = \"B\"\n",
    "\n",
    "    elif average >= 50:\n",
    "        grade = \"C\"\n",
    "\n",
    "    else:\n",
    "        grade = \"Fail\"\n",
    "\n",
    "    print(\"Student:\", name)\n",
    "    print(\"Total:\", total)\n",
    "    print(\"Average:\", average)\n",
    "    print(\"Grade:\", grade)\n",
    "\n",
    "student_result(\"Arya\", [85, 90, 78])\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8fcef080-4f83-432e-a5fb-d21f165c3929",
   "metadata": {},
   "outputs": [],
   "source": [
    "zero_shot_prompt = f\"\"\"\n",
    "Review the following Python code and suggest improvements:\n",
    "\n",
    "{code_sample}\n",
    "\"\"\"\n",
    "\n",
    "few_shot_prompt = f\"\"\"\n",
    "Example Review:\n",
    "\n",
    "Code:\n",
    "def add(a,b):\n",
    "    return a+b\n",
    "\n",
    "Review:\n",
    "- Add spaces after commas for readability.\n",
    "- Add a docstring explaining the function.\n",
    "- Handle invalid input types.\n",
    "\n",
    "Now review this code:\n",
    "\n",
    "{code_sample}\n",
    "\"\"\"\n",
    "\n",
    "chain_of_thought_prompt = f\"\"\"\n",
    "Review the following Python code step by step.\n",
    "\n",
    "Step 1: Check for bugs or logic errors.\n",
    "Step 2: Check coding style and readability.\n",
    "Step 3: Check security or input validation issues.\n",
    "Step 4: Suggest final improvements.\n",
    "\n",
    "Code:\n",
    "\n",
    "{code_sample}\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "3fe5fd49-3492-4b99-bd67-75636c6a6fb9",
   "metadata": {},
   "outputs": [],
   "source": [
    "prompts = {\n",
    "    \"Zero Shot\": zero_shot_prompt,\n",
    "    \"Few Shot\": few_shot_prompt,\n",
    "    \"Chain of Thought\": chain_of_thought_prompt\n",
    "}\n",
    "\n",
    "results = []"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "93334e9d-6524-49d2-9bde-b2f5e4f24f98",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "Zero Shot\n",
      "============================================================\n",
      "**Code Review and Improvements**\n",
      "\n",
      "The provided Python code calculates a student's grade based on their marks. Here are some suggestions for improvement:\n",
      "\n",
      "1. **Error Handling**: The function does not handle potential errors, such as an empty list of marks or a non-numeric value in the marks list. You can add error handling to make the function more robust.\n",
      "\n",
      "2. **Input Validation**: The function assumes that the input list `marks` is non-empty. However, it does not check for this. You can add input validation to ensure that the input list is non-empty and contains only numeric values.\n",
      "\n",
      "3. **Code Organization**: The code mixes the calculation of the average and the grade with the printing of the results. You can separate these into different functions to make the code more modular.\n",
      "\n",
      "4. **Type Hints**: The function parameters `name` and `marks` can have type hints to indicate the expected data types.\n",
      "\n",
      "5. **Constant Values**: The grade thresholds (90, 75, 50) are hardcoded in the function. You can define these as constant values to make the code more readable and maintainable.\n",
      "\n",
      "6. **Return Value**: The function prints the results directly. However, it would be more useful to return the results as a dictionary or a named tuple. This allows the caller to process the results as needed.\n",
      "\n",
      "Here's the improved code:\n",
      "\n",
      "```python\n",
      "def calculate_average(marks):\n",
      "    \"\"\"\n",
      "    Calculate the average of a list of numbers.\n",
      "\n",
      "    Args:\n",
      "        marks (list): A list of numeric values.\n",
      "\n",
      "    Returns:\n",
      "        float: The average of the marks.\n",
      "\n",
      "    Raises:\n",
      "        ValueError: If the input list is empty or contains non-numeric values.\n",
      "    \"\"\"\n",
      "    if not marks:\n",
      "        raise ValueError(\"Input list cannot be empty\")\n",
      "\n",
      "    if not all(isinstance(mark, (int, float)) for mark in marks):\n",
      "        raise ValueError(\"Input list must contain only numeric values\")\n",
      "\n",
      "    return sum(marks) / len(marks)\n",
      "\n",
      "\n",
      "def determine_grade(average):\n",
      "    \"\"\"\n",
      "    Determine the grade based on the average.\n",
      "\n",
      "    Args:\n",
      "        average (float): The average of the marks.\n",
      "\n",
      "    Returns:\n",
      "        str: The grade corresponding to the average.\n",
      "    \"\"\"\n",
      "    if average >= 90:\n",
      "        return \"A\"\n",
      "    elif average >= 75:\n",
      "        return \"B\"\n",
      "    elif average >= 50:\n",
      "        return \"C\"\n",
      "    else:\n",
      "        return \"Fail\"\n",
      "\n",
      "\n",
      "def student_result(name, marks):\n",
      "    \"\"\"\n",
      "    Calculate the student's result.\n",
      "\n",
      "    Args:\n",
      "        name (str): The student's name.\n",
      "        marks (list): A list of numeric values representing the student's marks.\n",
      "\n",
      "    Returns:\n",
      "        dict: A dictionary containing the student's result.\n",
      "    \"\"\"\n",
      "    average = calculate_average(marks)\n",
      "    grade = determine_grade(average)\n",
      "\n",
      "    return {\n",
      "        \"name\": name,\n",
      "        \"total\": sum(marks),\n",
      "        \"average\": average,\n",
      "        \"grade\": grade\n",
      "    }\n",
      "\n",
      "\n",
      "if __name__ == \"__main__\":\n",
      "    student_result(\"Arya\", [85, 90, 78])\n",
      "```\n",
      "\n",
      "In this improved code, the `calculate_average` function calculates the average of a list of numbers, and the `determine_grade` function determines the grade based on the average. The `student_result` function calculates the student's result and returns a dictionary containing the result. The input validation and error handling are also improved to make the code more robust.\n",
      "\n",
      "\n",
      "============================================================\n",
      "Few Shot\n",
      "============================================================\n",
      "Review:\n",
      "\n",
      "1. **Type hints:** Add type hints for the function parameters to improve readability and make it easier for other developers to understand the function signature.\n",
      "2. **Docstring:** Add a docstring to explain the purpose of the function and what it returns.\n",
      "3. **Input validation:** Handle invalid input types for the `name` and `marks` parameters. For example, if `name` is not a string or `marks` is not a list of numbers, the function should raise an error.\n",
      "4. **Error handling:** Add error handling for the case where `marks` is an empty list.\n",
      "5. **Separate calculation and printing:** Consider separating the calculation of the student result from the printing of the result to make the code more modular and reusable.\n",
      "6. **Naming:** Consider renaming the function to something more descriptive, such as `calculate_student_result`.\n",
      "7. **Magic numbers:** The numbers 90, 75, and 50 are magic numbers. Consider defining them as constants at the top of the file or in a separate constants module.\n",
      "8. **Return statement:** The function currently prints the result directly. However, it might be more useful to return the result instead, so that the caller can decide how to handle it.\n",
      "\n",
      "Here's an updated version of the code incorporating these suggestions:\n",
      "\n",
      "```python\n",
      "def calculate_student_result(name: str, marks: list[float]) -> None:\n",
      "    \"\"\"\n",
      "    Calculate the total marks and average of a student, and determine their grade.\n",
      "\n",
      "    Args:\n",
      "    name (str): The name of the student.\n",
      "    marks (list[float]): A list of marks obtained by the student.\n",
      "\n",
      "    Prints:\n",
      "    The student's name, total marks, average, and grade.\n",
      "    \"\"\"\n",
      "\n",
      "    # Check if input types are correct\n",
      "    if not isinstance(name, str):\n",
      "        raise ValueError(\"Name must be a string\")\n",
      "    if not isinstance(marks, list) or not all(isinstance(mark, (int, float)) for mark in marks):\n",
      "        raise ValueError(\"Marks must be a list of numbers\")\n",
      "\n",
      "    # Check if marks list is not empty\n",
      "    if len(marks) == 0:\n",
      "        raise ValueError(\"Marks list cannot be empty\")\n",
      "\n",
      "    # Calculate total and average marks\n",
      "    total_marks = sum(marks)\n",
      "    average_marks = total_marks / len(marks)\n",
      "\n",
      "    # Determine grade based on average marks\n",
      "    grade = \"A\" if average_marks >= 90 else \"B\" if average_marks >= 75 else \"C\" if average_marks >= 50 else \"Fail\"\n",
      "\n",
      "    # Print student's result\n",
      "    print(\"Student:\", name)\n",
      "    print(\"Total:\", total_marks)\n",
      "    print(\"Average:\", average_marks)\n",
      "    print(\"Grade:\", grade)\n",
      "\n",
      "# Example usage:\n",
      "calculate_student_result(\"Arya\", [85, 90, 78])\n",
      "```\n",
      "\n",
      "\n",
      "============================================================\n",
      "Chain of Thought\n",
      "============================================================\n",
      "**Step 1: Check for bugs or logic errors.**\n",
      "\n",
      "The code provided appears to be mostly correct, but there are a few potential issues:\n",
      "\n",
      "1.  The code does not handle the case where the input list `marks` is empty. This will raise a `ZeroDivisionError` when trying to calculate the average. To fix this, we can add a check to ensure that the list is not empty before calculating the average.\n",
      "2.  The code does not handle the case where the input list `marks` contains non-numeric values. This will raise a `TypeError` when trying to calculate the sum or average. To fix this, we can add a check to ensure that all values in the list are numeric.\n",
      "3.  The code does not handle the case where the input `name` is `None`. This will print `None` when printing the student's name. To fix this, we can add a check to ensure that the input `name` is not `None`.\n",
      "4.  The code does not handle the case where the input `marks` is not a list. This will raise a `TypeError` when trying to calculate the sum or average. To fix this, we can add a check to ensure that the input `marks` is a list.\n",
      "\n",
      "**Step 2: Check coding style and readability.**\n",
      "\n",
      "The code provided is mostly well-structured, but there are a few suggestions for improvement:\n",
      "\n",
      "1.  The function name `student_result` is not very descriptive. It would be better to rename it to something like `calculate_student_grade`.\n",
      "2.  The code uses a lot of magic numbers (e.g., 90, 75, 50). It would be better to define these numbers as constants at the top of the file.\n",
      "3.  The code uses a series of if-elif-else statements to determine the grade. This could be replaced with a more concise dictionary-based approach.\n",
      "4.  The code prints the student's name, total, average, and grade to the console. It would be better to return these values from the function instead of printing them directly.\n",
      "\n",
      "**Step 3: Check security or input validation issues.**\n",
      "\n",
      "The code provided does not have any obvious security vulnerabilities, but there are a few suggestions for improvement:\n",
      "\n",
      "1.  The code does not validate the input `name`. It would be better to ensure that the input `name` is a non-empty string.\n",
      "2.  The code does not validate the input `marks`. It would be better to ensure that the input `marks` is a non-empty list of numbers.\n",
      "3.  The code does not handle the case where the input `marks` contains very large numbers. This could cause a `OverflowError`. To fix this, we can add a check to ensure that the maximum value in the list is within a reasonable range.\n",
      "\n",
      "**Step 4: Suggest final improvements.**\n",
      "\n",
      "Here is a revised version of the code that addresses the issues mentioned above:\n",
      "\n",
      "```python\n",
      "# Define constants for the minimum grades\n",
      "MIN_A = 90\n",
      "MIN_B = 75\n",
      "MIN_C = 50\n",
      "\n",
      "def calculate_student_grade(name, marks):\n",
      "    \"\"\"\n",
      "    Calculate the grade of a student based on their marks.\n",
      "\n",
      "    Args:\n",
      "        name (str): The name of the student.\n",
      "        marks (list): A list of marks scored by the student.\n",
      "\n",
      "    Returns:\n",
      "        dict: A dictionary containing the student's name, total, average, and grade.\n",
      "    \"\"\"\n",
      "\n",
      "    # Validate the input name\n",
      "    if not isinstance(name, str) or not name.strip():\n",
      "        raise ValueError(\"Invalid student name\")\n",
      "\n",
      "    # Validate the input marks\n",
      "    if not isinstance(marks, list) or len(marks) == 0:\n",
      "        raise ValueError(\"Invalid marks\")\n",
      "    if not all(isinstance(mark, (int, float)) for mark in marks):\n",
      "        raise ValueError(\"Invalid marks\")\n",
      "\n",
      "    # Calculate the total and average marks\n",
      "    total = sum(marks)\n",
      "    average = total / len(marks)\n",
      "\n",
      "    # Determine the grade based on the average\n",
      "    grades = {\n",
      "        \"A\": lambda x: x >= MIN_A,\n",
      "        \"B\": lambda x: x >= MIN_B and x < MIN_A,\n",
      "        \"C\": lambda x: x >= MIN_C and x < MIN_B,\n",
      "        \"Fail\": lambda x: x < MIN_C\n",
      "    }\n",
      "    grade = next((key for key, predicate in grades.items() if predicate(average)), \"Fail\")\n",
      "\n",
      "    return {\n",
      "        \"name\": name,\n",
      "        \"total\": total,\n",
      "        \"average\": average,\n",
      "        \"grade\": grade\n",
      "    }\n",
      "\n",
      "# Example usage\n",
      "student = calculate_student_grade(\"Arya\", [85, 90, 78])\n",
      "print(student)\n",
      "```\n",
      "\n",
      "This revised version of the code is more robust, readable, and maintainable. It includes input validation, uses a more concise dictionary-based approach to determine the grade, and returns a dictionary containing the student's name, total, average, and grade.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "for prompt_type, prompt_text in prompts.items():\n",
    "\n",
    "    input_tokens = len(encoding.encode(prompt_text))\n",
    "\n",
    "    start_time = time.time()\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=[\n",
    "            {\n",
    "                \"role\": \"user\",\n",
    "                \"content\": prompt_text\n",
    "            }\n",
    "        ],\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    end_time = time.time()\n",
    "\n",
    "    output_text = response.choices[0].message.content\n",
    "\n",
    "    response_time = end_time - start_time\n",
    "\n",
    "    output_length = len(output_text)\n",
    "\n",
    "    results.append({\n",
    "        \"prompt_type\": prompt_type,\n",
    "        \"input_tokens\": input_tokens,\n",
    "        \"response_time\": round(response_time, 2),\n",
    "        \"output_length\": output_length\n",
    "    })\n",
    "\n",
    "    print(\"=\" * 60)\n",
    "    print(prompt_type)\n",
    "    print(\"=\" * 60)\n",
    "\n",
    "    print(output_text)\n",
    "    print(\"\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "13f3e2fc-5b9c-4a7c-83fd-9040856567b3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "        prompt_type  input_tokens  response_time  output_length\n",
      "0         Zero Shot           125           1.43           3209\n",
      "1          Few Shot           161           1.27           2532\n",
      "2  Chain of Thought           168           2.09           4309\n"
     ]
    }
   ],
   "source": [
    "df = pd.DataFrame(results)\n",
    "\n",
    "print(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fd00bbbf-8b81-44bb-95d0-60e9d748f862",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
