{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0602ee31-f276-4e15-9266-b75012e840d2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "Turn 1\n",
      "============================================================\n",
      "User: What is a list in Python?\n",
      "Assistant: **Lists in Python**\n",
      "=====================\n",
      "\n",
      "In Python, a list is a collection of items that can be of any data type, including strings, integers, floats, and other lists. Lists are denoted by square brackets `[]` and are ordered, meaning that each item has a specific position or index.\n",
      "\n",
      "Here's a basic example of a list:\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "```\n",
      "\n",
      "**Key Characteristics of Lists**\n",
      "\n",
      "1. **Ordered**: Lists maintain the order in which items were added.\n",
      "2. **Indexed**: Each item in a list has a specific index or position.\n",
      "3. **Mutable**: Lists can be modified after creation.\n",
      "4. **Heterogeneous**: Lists can contain items of different data types.\n",
      "\n",
      "**Basic List Operations**\n",
      "-------------------------\n",
      "\n",
      "### Indexing and Slicing\n",
      "\n",
      "You can access individual items in a list using their index:\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "print(my_list[0])  # Output: 1\n",
      "```\n",
      "\n",
      "You can also slice lists to extract a subset of items:\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "print(my_list[1:3])  # Output: [2, 3]\n",
      "```\n",
      "\n",
      "### List Methods\n",
      "\n",
      "Python lists provide several built-in methods for common operations:\n",
      "\n",
      "* `append(item)`: Adds an item to the end of the list.\n",
      "* `insert(index, item)`: Inserts an item at a specified index.\n",
      "* `remove(item)`: Removes the first occurrence of an item.\n",
      "* `sort()`: Sorts the list in-place.\n",
      "* `reverse()`: Reverses the order of the list.\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "my_list.append(6)\n",
      "print(my_list)  # Output: [1, 2, 3, 4, 5, 6]\n",
      "\n",
      "my_list.sort()\n",
      "print(my_list)  # Output: [1, 2, 3, 4, 5, 6]\n",
      "```\n",
      "\n",
      "### List Comprehensions\n",
      "\n",
      "List comprehensions are a concise way to create new lists from existing ones:\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3, 4, 5]\n",
      "squared_list = [x ** 2 for x in my_list]\n",
      "print(squared_list)  # Output: [1, 4, 9, 16, 25]\n",
      "```\n",
      "\n",
      "============================================================\n",
      "Turn 2\n",
      "============================================================\n",
      "User: How is it different from a tuple?\n",
      "Assistant: **Lists vs Tuples in Python**\n",
      "=============================\n",
      "\n",
      "Lists and tuples are both data structures in Python used to store multiple values, but they have some key differences:\n",
      "\n",
      "### 1. **Immutability**\n",
      "\n",
      "* **Lists**: Lists are **mutable**, meaning their contents can be modified after creation. You can add, remove, or change items in a list.\n",
      "* **Tuples**: Tuples are **immutable**, meaning their contents cannot be modified after creation. Attempting to modify a tuple will result in a `TypeError`.\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3]\n",
      "my_list.append(4)  # OK, list is mutable\n",
      "\n",
      "my_tuple = (1, 2, 3)\n",
      "try:\n",
      "    my_tuple.append(4)  # Raises TypeError\n",
      "except TypeError:\n",
      "    print(\"Tuples are immutable\")\n",
      "```\n",
      "\n",
      "### 2. **Syntax**\n",
      "\n",
      "* **Lists**: Lists are denoted by square brackets `[]`.\n",
      "* **Tuples**: Tuples are denoted by parentheses `()`.\n",
      "\n",
      "```python\n",
      "my_list = [1, 2, 3]\n",
      "my_tuple = (1, 2, 3)\n",
      "```\n",
      "\n",
      "### 3. **Performance**\n",
      "\n",
      "* **Lists**: Lists are generally slower and more memory-intensive than tuples because they have more overhead for dynamic memory allocation.\n",
      "* **Tuples**: Tuples are faster and use less memory than lists because they are immutable and can be stored more efficiently.\n",
      "\n",
      "### 4. **Use Cases**\n",
      "\n",
      "* **Lists**: Use lists when you need to store a collection of items that may change frequently, such as a shopping cart or a dynamic data structure.\n",
      "* **Tuples**: Use tuples when you need a fixed, unchanging collection of items, such as a record, a point in space, or a small dataset.\n",
      "\n",
      "In summary, if you need a collection of items that can change, use a list. If you need a fixed, unchanging collection of items, use a tuple.\n",
      "\n",
      "**When to Choose Tuples Over Lists**\n",
      "\n",
      "* Use tuples when:\n",
      "\t+ You need a small, fixed dataset.\n",
      "\t+ You need to store a record or a point in space.\n",
      "\t+ You need a lightweight, immutable data structure.\n",
      "\t+ You need to optimize performance and memory usage.\n",
      "\n",
      "```python\n",
      "# Using a tuple for a small dataset\n",
      "data = (1, 2, 3, 4, 5)\n",
      "```\n",
      "\n",
      "**When to Choose Lists Over Tuples**\n",
      "\n",
      "* Use lists when:\n",
      "\t+ You need a collection of items that may change frequently.\n",
      "\t+ You need a dynamic data structure that can grow or shrink.\n",
      "\t+ You need to store a large dataset that may be modified.\n",
      "\n",
      "```python\n",
      "# Using a list for a dynamic data structure\n",
      "data = []\n",
      "data.append(1)\n",
      "data.append(2)\n",
      "data.append(3)\n",
      "```\n",
      "\n",
      "============================================================\n",
      "Turn 3\n",
      "============================================================\n",
      "User: Can you give an example of list slicing?\n",
      "Assistant: **List Slicing in Python**\n",
      "==========================\n",
      "\n",
      "List slicing is a powerful feature in Python that allows you to extract a subset of elements from a list. It's a convenient way to work with lists and is commonly used in many applications.\n",
      "\n",
      "**Basic Syntax**\n",
      "---------------\n",
      "\n",
      "The basic syntax for list slicing is:\n",
      "\n",
      "```python\n",
      "list[start:stop:step]\n",
      "```\n",
      "\n",
      "* `start`: The starting index of the slice (inclusive).\n",
      "* `stop`: The ending index of the slice (exclusive).\n",
      "* `step`: The increment between indices (default is 1).\n",
      "\n",
      "**Example 1: Basic Slicing**\n",
      "---------------------------\n",
      "\n",
      "Let's create a list and slice it to get the middle three elements:\n",
      "\n",
      "```python\n",
      "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\n",
      "middle_numbers = numbers[3:6]\n",
      "print(middle_numbers)  # Output: [4, 5, 6]\n",
      "```\n",
      "\n",
      "**Example 2: Slicing with Negative Indices**\n",
      "-----------------------------------------\n",
      "\n",
      "Negative indices are used to count from the end of the list:\n",
      "\n",
      "```python\n",
      "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\n",
      "last_three_numbers = numbers[-3:]\n",
      "print(last_three_numbers)  # Output: [7, 8, 9]\n",
      "```\n",
      "\n",
      "**Example 3: Slicing with a Step**\n",
      "-------------------------------\n",
      "\n",
      "You can use a step to extract every nth element:\n",
      "\n",
      "```python\n",
      "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\n",
      "every_other_number = numbers[0:9:2]\n",
      "print(every_other_number)  # Output: [1, 3, 5, 7, 9]\n",
      "```\n",
      "\n",
      "**Example 4: Slicing with a Step of -1**\n",
      "--------------------------------------\n",
      "\n",
      "This will also give you every nth element, but in reverse order:\n",
      "\n",
      "```python\n",
      "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\n",
      "every_other_number = numbers[0:9:-2]\n",
      "print(every_other_number)  # Output: [1, 5, 9]\n",
      "```\n",
      "\n",
      "**Example 5: Slicing with a Large Step**\n",
      "--------------------------------------\n",
      "\n",
      "This will give you every nth element, where n is the step value:\n",
      "\n",
      "```python\n",
      "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\n",
      "every_fifth_number = numbers[::5]\n",
      "print(every_fifth_number)  # Output: [1, 6]\n",
      "```\n",
      "\n",
      "**Example 6: Slicing with a Step of 0**\n",
      "--------------------------------------\n",
      "\n",
      "This will give you every nth element, but if n is 0, it will raise an error:\n",
      "\n",
      "```python\n",
      "numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\n",
      "try:\n",
      "    every_nth_number = numbers[::0]\n",
      "except ValueError:\n",
      "    print(\"Cannot slice with a step of 0\")\n",
      "```\n",
      "\n",
      "============================================================\n",
      "Turn 4\n",
      "============================================================\n",
      "User: What happens if I try to modify a tuple?\n",
      "Assistant: **Tuples are Immutable in Python**\n",
      "=====================================\n",
      "\n",
      "In Python, tuples are immutable data structures, which means that their contents cannot be modified after they are created. If you try to modify a tuple, you will get a `TypeError`.\n",
      "\n",
      "**Example**\n",
      "---------\n",
      "\n",
      "Here's an example of trying to modify a tuple:\n",
      "\n",
      "```python\n",
      "my_tuple = (1, 2, 3)\n",
      "try:\n",
      "    my_tuple[0] = 10  # Trying to modify the first element\n",
      "except TypeError:\n",
      "    print(\"Tuples are immutable\")\n",
      "```\n",
      "\n",
      "When you run this code, you will get the following output:\n",
      "\n",
      "```\n",
      "Tuples are immutable\n",
      "```\n",
      "\n",
      "**Why Tuples are Immutable**\n",
      "---------------------------\n",
      "\n",
      "Tuples are designed to be immutable for several reasons:\n",
      "\n",
      "1. **Thread safety**: If tuples were mutable, it would be difficult to ensure thread safety in multi-threaded environments.\n",
      "2. **Cache efficiency**: Immutable tuples can be stored in cache more efficiently, which can improve performance.\n",
      "3. **Code simplicity**: Immutable tuples make code simpler and more predictable, as you don't need to worry about side effects.\n",
      "\n",
      "**What Happens if You Try to Modify a Tuple Using Assignment?**\n",
      "---------------------------------------------------------\n",
      "\n",
      "If you try to assign a new value to an element of a tuple, you will get a `TypeError`. However, if you try to assign a new tuple to a variable, you can still modify the contents of the tuple.\n",
      "\n",
      "Here's an example:\n",
      "\n",
      "```python\n",
      "my_tuple = (1, 2, 3)\n",
      "my_tuple = (10, 20, 30)  # Assigning a new tuple to the variable\n",
      "print(my_tuple)  # Output: (10, 20, 30)\n",
      "```\n",
      "\n",
      "In this example, we are not modifying the original tuple, but rather assigning a new tuple to the variable `my_tuple`.\n",
      "\n",
      "**What Happens if You Try to Modify a Tuple Using List Methods?**\n",
      "----------------------------------------------------------------\n",
      "\n",
      "If you try to use list methods like `append()`, `insert()`, or `remove()` on a tuple, you will get a `TypeError`.\n",
      "\n",
      "Here's an example:\n",
      "\n",
      "```python\n",
      "my_tuple = (1, 2, 3)\n",
      "try:\n",
      "    my_tuple.append(4)  # Trying to use list method on a tuple\n",
      "except TypeError:\n",
      "    print(\"Tuples are immutable\")\n",
      "```\n",
      "\n",
      "When you run this code, you will get the following output:\n",
      "\n",
      "```\n",
      "Tuples are immutable\n",
      "```\n",
      "\n",
      "In summary, tuples are immutable in Python, and trying to modify them will result in a `TypeError`. However, you can still assign a new tuple to a variable, and use tuple unpacking to extract elements from a tuple.\n",
      "\n",
      "============================================================\n",
      "Full Conversation History\n",
      "============================================================\n",
      "{'role': 'system', 'content': 'You are a helpful Python doubt solver.'}\n",
      "{'role': 'user', 'content': 'What is a list in Python?'}\n",
      "{'role': 'assistant', 'content': \"**Lists in Python**\\n=====================\\n\\nIn Python, a list is a collection of items that can be of any data type, including strings, integers, floats, and other lists. Lists are denoted by square brackets `[]` and are ordered, meaning that each item has a specific position or index.\\n\\nHere's a basic example of a list:\\n\\n```python\\nmy_list = [1, 2, 3, 4, 5]\\n```\\n\\n**Key Characteristics of Lists**\\n\\n1. **Ordered**: Lists maintain the order in which items were added.\\n2. **Indexed**: Each item in a list has a specific index or position.\\n3. **Mutable**: Lists can be modified after creation.\\n4. **Heterogeneous**: Lists can contain items of different data types.\\n\\n**Basic List Operations**\\n-------------------------\\n\\n### Indexing and Slicing\\n\\nYou can access individual items in a list using their index:\\n\\n```python\\nmy_list = [1, 2, 3, 4, 5]\\nprint(my_list[0])  # Output: 1\\n```\\n\\nYou can also slice lists to extract a subset of items:\\n\\n```python\\nmy_list = [1, 2, 3, 4, 5]\\nprint(my_list[1:3])  # Output: [2, 3]\\n```\\n\\n### List Methods\\n\\nPython lists provide several built-in methods for common operations:\\n\\n* `append(item)`: Adds an item to the end of the list.\\n* `insert(index, item)`: Inserts an item at a specified index.\\n* `remove(item)`: Removes the first occurrence of an item.\\n* `sort()`: Sorts the list in-place.\\n* `reverse()`: Reverses the order of the list.\\n\\n```python\\nmy_list = [1, 2, 3, 4, 5]\\nmy_list.append(6)\\nprint(my_list)  # Output: [1, 2, 3, 4, 5, 6]\\n\\nmy_list.sort()\\nprint(my_list)  # Output: [1, 2, 3, 4, 5, 6]\\n```\\n\\n### List Comprehensions\\n\\nList comprehensions are a concise way to create new lists from existing ones:\\n\\n```python\\nmy_list = [1, 2, 3, 4, 5]\\nsquared_list = [x ** 2 for x in my_list]\\nprint(squared_list)  # Output: [1, 4, 9, 16, 25]\\n```\"}\n",
      "{'role': 'user', 'content': 'How is it different from a tuple?'}\n",
      "{'role': 'assistant', 'content': '**Lists vs Tuples in Python**\\n=============================\\n\\nLists and tuples are both data structures in Python used to store multiple values, but they have some key differences:\\n\\n### 1. **Immutability**\\n\\n* **Lists**: Lists are **mutable**, meaning their contents can be modified after creation. You can add, remove, or change items in a list.\\n* **Tuples**: Tuples are **immutable**, meaning their contents cannot be modified after creation. Attempting to modify a tuple will result in a `TypeError`.\\n\\n```python\\nmy_list = [1, 2, 3]\\nmy_list.append(4)  # OK, list is mutable\\n\\nmy_tuple = (1, 2, 3)\\ntry:\\n    my_tuple.append(4)  # Raises TypeError\\nexcept TypeError:\\n    print(\"Tuples are immutable\")\\n```\\n\\n### 2. **Syntax**\\n\\n* **Lists**: Lists are denoted by square brackets `[]`.\\n* **Tuples**: Tuples are denoted by parentheses `()`.\\n\\n```python\\nmy_list = [1, 2, 3]\\nmy_tuple = (1, 2, 3)\\n```\\n\\n### 3. **Performance**\\n\\n* **Lists**: Lists are generally slower and more memory-intensive than tuples because they have more overhead for dynamic memory allocation.\\n* **Tuples**: Tuples are faster and use less memory than lists because they are immutable and can be stored more efficiently.\\n\\n### 4. **Use Cases**\\n\\n* **Lists**: Use lists when you need to store a collection of items that may change frequently, such as a shopping cart or a dynamic data structure.\\n* **Tuples**: Use tuples when you need a fixed, unchanging collection of items, such as a record, a point in space, or a small dataset.\\n\\nIn summary, if you need a collection of items that can change, use a list. If you need a fixed, unchanging collection of items, use a tuple.\\n\\n**When to Choose Tuples Over Lists**\\n\\n* Use tuples when:\\n\\t+ You need a small, fixed dataset.\\n\\t+ You need to store a record or a point in space.\\n\\t+ You need a lightweight, immutable data structure.\\n\\t+ You need to optimize performance and memory usage.\\n\\n```python\\n# Using a tuple for a small dataset\\ndata = (1, 2, 3, 4, 5)\\n```\\n\\n**When to Choose Lists Over Tuples**\\n\\n* Use lists when:\\n\\t+ You need a collection of items that may change frequently.\\n\\t+ You need a dynamic data structure that can grow or shrink.\\n\\t+ You need to store a large dataset that may be modified.\\n\\n```python\\n# Using a list for a dynamic data structure\\ndata = []\\ndata.append(1)\\ndata.append(2)\\ndata.append(3)\\n```'}\n",
      "{'role': 'user', 'content': 'Can you give an example of list slicing?'}\n",
      "{'role': 'assistant', 'content': '**List Slicing in Python**\\n==========================\\n\\nList slicing is a powerful feature in Python that allows you to extract a subset of elements from a list. It\\'s a convenient way to work with lists and is commonly used in many applications.\\n\\n**Basic Syntax**\\n---------------\\n\\nThe basic syntax for list slicing is:\\n\\n```python\\nlist[start:stop:step]\\n```\\n\\n* `start`: The starting index of the slice (inclusive).\\n* `stop`: The ending index of the slice (exclusive).\\n* `step`: The increment between indices (default is 1).\\n\\n**Example 1: Basic Slicing**\\n---------------------------\\n\\nLet\\'s create a list and slice it to get the middle three elements:\\n\\n```python\\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\\nmiddle_numbers = numbers[3:6]\\nprint(middle_numbers)  # Output: [4, 5, 6]\\n```\\n\\n**Example 2: Slicing with Negative Indices**\\n-----------------------------------------\\n\\nNegative indices are used to count from the end of the list:\\n\\n```python\\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\\nlast_three_numbers = numbers[-3:]\\nprint(last_three_numbers)  # Output: [7, 8, 9]\\n```\\n\\n**Example 3: Slicing with a Step**\\n-------------------------------\\n\\nYou can use a step to extract every nth element:\\n\\n```python\\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\\nevery_other_number = numbers[0:9:2]\\nprint(every_other_number)  # Output: [1, 3, 5, 7, 9]\\n```\\n\\n**Example 4: Slicing with a Step of -1**\\n--------------------------------------\\n\\nThis will also give you every nth element, but in reverse order:\\n\\n```python\\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\\nevery_other_number = numbers[0:9:-2]\\nprint(every_other_number)  # Output: [1, 5, 9]\\n```\\n\\n**Example 5: Slicing with a Large Step**\\n--------------------------------------\\n\\nThis will give you every nth element, where n is the step value:\\n\\n```python\\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\\nevery_fifth_number = numbers[::5]\\nprint(every_fifth_number)  # Output: [1, 6]\\n```\\n\\n**Example 6: Slicing with a Step of 0**\\n--------------------------------------\\n\\nThis will give you every nth element, but if n is 0, it will raise an error:\\n\\n```python\\nnumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]\\ntry:\\n    every_nth_number = numbers[::0]\\nexcept ValueError:\\n    print(\"Cannot slice with a step of 0\")\\n```'}\n",
      "{'role': 'user', 'content': 'What happens if I try to modify a tuple?'}\n",
      "{'role': 'assistant', 'content': '**Tuples are Immutable in Python**\\n=====================================\\n\\nIn Python, tuples are immutable data structures, which means that their contents cannot be modified after they are created. If you try to modify a tuple, you will get a `TypeError`.\\n\\n**Example**\\n---------\\n\\nHere\\'s an example of trying to modify a tuple:\\n\\n```python\\nmy_tuple = (1, 2, 3)\\ntry:\\n    my_tuple[0] = 10  # Trying to modify the first element\\nexcept TypeError:\\n    print(\"Tuples are immutable\")\\n```\\n\\nWhen you run this code, you will get the following output:\\n\\n```\\nTuples are immutable\\n```\\n\\n**Why Tuples are Immutable**\\n---------------------------\\n\\nTuples are designed to be immutable for several reasons:\\n\\n1. **Thread safety**: If tuples were mutable, it would be difficult to ensure thread safety in multi-threaded environments.\\n2. **Cache efficiency**: Immutable tuples can be stored in cache more efficiently, which can improve performance.\\n3. **Code simplicity**: Immutable tuples make code simpler and more predictable, as you don\\'t need to worry about side effects.\\n\\n**What Happens if You Try to Modify a Tuple Using Assignment?**\\n---------------------------------------------------------\\n\\nIf you try to assign a new value to an element of a tuple, you will get a `TypeError`. However, if you try to assign a new tuple to a variable, you can still modify the contents of the tuple.\\n\\nHere\\'s an example:\\n\\n```python\\nmy_tuple = (1, 2, 3)\\nmy_tuple = (10, 20, 30)  # Assigning a new tuple to the variable\\nprint(my_tuple)  # Output: (10, 20, 30)\\n```\\n\\nIn this example, we are not modifying the original tuple, but rather assigning a new tuple to the variable `my_tuple`.\\n\\n**What Happens if You Try to Modify a Tuple Using List Methods?**\\n----------------------------------------------------------------\\n\\nIf you try to use list methods like `append()`, `insert()`, or `remove()` on a tuple, you will get a `TypeError`.\\n\\nHere\\'s an example:\\n\\n```python\\nmy_tuple = (1, 2, 3)\\ntry:\\n    my_tuple.append(4)  # Trying to use list method on a tuple\\nexcept TypeError:\\n    print(\"Tuples are immutable\")\\n```\\n\\nWhen you run this code, you will get the following output:\\n\\n```\\nTuples are immutable\\n```\\n\\nIn summary, tuples are immutable in Python, and trying to modify them will result in a `TypeError`. However, you can still assign a new tuple to a variable, and use tuple unpacking to extract elements from a tuple.'}\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")\n",
    "\n",
    "messages = [\n",
    "    {\n",
    "        \"role\": \"system\",\n",
    "        \"content\": \"You are a helpful Python doubt solver.\"\n",
    "    }\n",
    "]\n",
    "\n",
    "questions = [\n",
    "    \"What is a list in Python?\",\n",
    "    \"How is it different from a tuple?\",\n",
    "    \"Can you give an example of list slicing?\",\n",
    "    \"What happens if I try to modify a tuple?\"\n",
    "]\n",
    "\n",
    "turn = 1\n",
    "\n",
    "for question in questions:\n",
    "\n",
    "    print(\"=\" * 60)\n",
    "    print(f\"Turn {turn}\")\n",
    "    print(\"=\" * 60)\n",
    "\n",
    "    print(\"User:\", question)\n",
    "\n",
    "    messages.append(\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": question\n",
    "        }\n",
    "    )\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=messages,\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    reply = response.choices[0].message.content\n",
    "\n",
    "    print(\"Assistant:\", reply)\n",
    "    print()\n",
    "\n",
    "    messages.append(\n",
    "        {\n",
    "            \"role\": \"assistant\",\n",
    "            \"content\": reply\n",
    "        }\n",
    "    )\n",
    "\n",
    "    turn += 1\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"Full Conversation History\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "for msg in messages:\n",
    "    print(msg)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ed83ee84-5bff-4b13-ba07-46147f9cc770",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
